# ========================================
# CONFIGURAÇÕES DE HARDWARE E CONSOLE
# ========================================
CONFIG_GPIO=y
CONFIG_ADC=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y

# ========================================
# ZBUS (Barramento de Mensagens)
# ========================================
CONFIG_ZBUS=y

# ========================================
# REDE, WI-FI E NET_MGMT
# ========================================
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_TCP=y
CONFIG_NET_UDP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_WIFI=y
CONFIG_WIFI_ESP32=y
CONFIG_NET_L2_WIFI_MGMT=y
CONFIG_NET_DHCPV4=y

# ========================================
# ATIVAR A SHELL DO ZEPHYR (Novidade aqui)
# ========================================
CONFIG_SHELL=y
CONFIG_SHELL_STACK_SIZE=4096

# ========================================
# CONFIGURAÇÕES DE MEMÓRIA
# ========================================
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_HEAP_MEM_POOL_SIZE=8192